---
- name: Setup K8s Worker
  hosts: localhost
  become: yes
  tasks:
    - name: Include Kubernetes Role
      include_role:
        name: kubernetes
      vars:
        k8s_role: 'worker'

    # --- ÉTAPE DE SÉCURITÉ : Nettoyage automatique si la jointure est nécessaire ---
    - name: Clean previous failed join attempts
      command: kubeadm reset -f
      when: join_command is defined
      args:
        creates: /etc/kubernetes/kubelet.conf # Ne nettoie PAS si le worker est déjà opérationnel

    - name: Join Worker to Cluster
      shell: "{{ join_command }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
      when: join_command is defined
