---
- name: Setup Kubernetes Worker
  hosts: localhost
  become: yes

  vars:
    k8s_role: "worker"

  tasks:

    - name: Include Kubernetes Role
      include_role:
        name: kubernetes

    - name: Reset previous failed join
      command: kubeadm reset -f
      when: global_join_command is defined
      ignore_errors: yes

    - name: Join worker to cluster
      command: >
        {{ hostvars['localhost'].global_join_command }}
        --cri-socket unix:///run/containerd/containerd.sock
      args:
        creates: /etc/kubernetes/kubelet.conf
      when: hostvars['localhost'].global_join_command is defined
