---
- name: Setup K8s Worker
  hosts: localhost
  become: yes
  tasks:
    - name: Include Kubernetes Role
      include_role:
        name: kubernetes
      vars:
        k8s_role: 'worker'

    # Nettoyage si le fichier kubelet.conf n'existe pas encore (signe que le join n'est pas fait)
    - name: Clean previous failed join attempts
      command: kubeadm reset -f
      when: join_command is defined
      args:
        creates: /etc/kubernetes/kubelet.conf

    # Jointure avec spécification explicite du socket containerd pour éviter l'erreur "unknown flag"
    - name: Join Worker to Cluster
      shell: "{{ join_command }} --cri-socket unix:///var/run/containerd/containerd.sock"
      args:
        creates: /etc/kubernetes/kubelet.conf
      when: 
        - join_command is defined
        - join_command != ""
