---
- name: Setup Kubernetes Worker
  hosts: localhost
  become: yes
  vars:
    k8s_role: "worker"
    join_file: "/etc/kubernetes/join-command.sh"

  tasks:
    - name: Run Base Kubernetes Role (Prerequisites & Binaries)
      include_role:
        [cite_start]name: roles/kubernetes [cite: 13, 27]

    - name: Join Cluster
      shell: |
        if [ ! -f /etc/kubernetes/kubelet.conf ]; then
          bash {{ join_file }} --cri-socket unix:///run/containerd/containerd.sock
        fi
      [cite_start]become: yes [cite: 22, 27]
