apiVersion: apps/v1
kind: Deployment

metadata:
  name: mono-backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: mono-backend

  template:
    metadata:
      labels:
        app: mono-backend

    spec:
      containers:
        - name: mono-backend
          image: raniaat12/mono-backend:f9f8e106ed6a760ad864bd0d8d802bc9043c0933
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SPRING_APPLICATION_NAME

            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SERVER_PORT
