apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: raniaat12/antigravity-flask:latest
          ports:
            - containerPort: 5000
          env:
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: flask-secrets
                  key: RESEND_API_KEY
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: flask-secrets
                  key: GROQ_API_KEY
