apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-api
  type: LoadBalancer # <--- Indispensable pour MetalLB
  ports:
    - port: 80         # Port exposé à l'extérieur
      targetPort: 5000 # Port interne de ton container Flask
