apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: raniaat12/front:0d8773ee0ab1bb51357512adae43e5f21b6a4b0c
          imagePullPolicy: Always
          ports:
            - containerPort: 80
