apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: raniaat12/front:31bbc7cfd0cdbf67b051e3b5821c4340d71fb83f
          imagePullPolicy: Always
          ports:
            - containerPort: 80
