apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: raniaat12/front:e5073349531eeb0bed91f1442d6bedac0b14bc41
          imagePullPolicy: Always
          ports:
            - containerPort: 80
